/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/http';
import * as import7 from '../../app/products/product.module';
import * as import8 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as import9 from '../../app/app-routing.module';
import * as import10 from '../../app/in-memory-data.service';
import * as import11 from '../../app/products/product.service';
import * as import12 from '../../app/hero.service';
import * as import13 from '../../app/hero-guard.service';
import * as import14 from './products/product-list.component.ngfactory';
import * as import15 from './products/product-detail.component.ngfactory';
import * as import16 from './products/product-edit.component.ngfactory';
import * as import17 from './dashboard.component.ngfactory';
import * as import18 from './hero-lite.component.ngfactory';
import * as import19 from './heroes.component.ngfactory';
import * as import20 from './app.component.ngfactory';
import * as import21 from '../../app/products/product-list.component';
import * as import22 from '../../app/products/product-detail.component';
import * as import23 from '../../app/products/product-edit.component';
import * as import24 from '../../app/dashboard.component';
import * as import25 from '../../app/hero-lite.component';
import * as import26 from '../../app/heroes.component';
import * as import27 from 'angular-in-memory-web-api/in-memory-backend.service';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵba_10:import5.ɵba;
  _FormsModule_11:import5.FormsModule;
  _HttpModule_12:import6.HttpModule;
  _ɵa_13:any;
  _UrlSerializer_14:import3.DefaultUrlSerializer;
  _RouterOutletMap_15:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_16:any;
  _LocationStrategy_17:any;
  _Location_18:import2.Location;
  _Compiler_19:import0.Compiler;
  _NgModuleFactoryLoader_20:import0.SystemJsNgModuleLoader;
  _ROUTES_21:any[];
  _Router_22:any;
  _RouterModule_23:import3.RouterModule;
  _ProductModule_24:import7.ProductModule;
  _InMemoryWebApiModule_25:import8.InMemoryWebApiModule;
  _AppRoutingModule_26:import9.AppRoutingModule;
  _AppModule_27:import1.AppModule;
  __LOCALE_ID_28:any;
  __NgLocalization_29:import2.NgLocaleLocalization;
  __APP_ID_30:any;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __DomSanitizer_33:import4.ɵe;
  __Sanitizer_34:any;
  __HAMMER_GESTURE_CONFIG_35:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_36:any[];
  __EventManager_37:import4.EventManager;
  __ɵDomSharedStylesHost_38:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_39:import4.ɵDomRendererFactory2;
  __RendererFactory2_40:any;
  __ɵSharedStylesHost_41:any;
  __Testability_42:import0.Testability;
  __Meta_43:import4.Meta;
  __Title_44:import4.Title;
  __ɵi_45:import5.ɵi;
  __InMemoryDbService_46:import10.InMemoryDataService;
  _InMemoryBackendConfig_47:any;
  __XHRBackend_48:any;
  __RequestOptions_49:import6.BaseRequestOptions;
  __Http_50:any;
  __BrowserXhr_51:import6.BrowserXhr;
  __ResponseOptions_52:import6.BaseResponseOptions;
  __XSRFStrategy_53:any;
  __ProductService_54:import11.ProductService;
  __ActivatedRoute_55:any;
  __NoPreloading_56:import3.NoPreloading;
  __PreloadingStrategy_57:any;
  __RouterPreloader_58:import3.RouterPreloader;
  __PreloadAllModules_59:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_60:any;
  __APP_BOOTSTRAP_LISTENER_61:any[];
  __HeroService_62:import12.HeroService;
  __HeroDetailGuard_63:import13.HeroDetailGuard;
  constructor(parent:import0.Injector) {
    super(parent,[
      import14.ProductListComponentNgFactory,
      import15.ProductDetailComponentNgFactory,
      import16.ProductEditComponentNgFactory,
      import17.DashboardComponentNgFactory,
      import18.HeroLiteComponentNgFactory,
      import19.HeroesComponentNgFactory,
      import20.AppComponentNgFactory
    ]
    ,[import20.AppComponentNgFactory]);
  }
  get _LOCALE_ID_28():any {
    if ((this.__LOCALE_ID_28 == null)) { (this.__LOCALE_ID_28 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_28;
  }
  get _NgLocalization_29():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_29 == null)) { (this.__NgLocalization_29 = new import2.NgLocaleLocalization(this._LOCALE_ID_28)); }
    return this.__NgLocalization_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == null)) { (this.__APP_ID_30 = import0.ɵg()); }
    return this.__APP_ID_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == null)) { (this.__IterableDiffers_31 = import0.ɵl()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == null)) { (this.__KeyValueDiffers_32 = import0.ɵm()); }
    return this.__KeyValueDiffers_32;
  }
  get _DomSanitizer_33():import4.ɵe {
    if ((this.__DomSanitizer_33 == null)) { (this.__DomSanitizer_33 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_33;
  }
  get _Sanitizer_34():any {
    if ((this.__Sanitizer_34 == null)) { (this.__Sanitizer_34 = this._DomSanitizer_33); }
    return this.__Sanitizer_34;
  }
  get _HAMMER_GESTURE_CONFIG_35():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_35 == null)) { (this.__HAMMER_GESTURE_CONFIG_35 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_35;
  }
  get _EVENT_MANAGER_PLUGINS_36():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_36 == null)) { (this.__EVENT_MANAGER_PLUGINS_36 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_35)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_36;
  }
  get _EventManager_37():import4.EventManager {
    if ((this.__EventManager_37 == null)) { (this.__EventManager_37 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_36,this.parent.get(import0.NgZone))); }
    return this.__EventManager_37;
  }
  get _ɵDomSharedStylesHost_38():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_38 == null)) { (this.__ɵDomSharedStylesHost_38 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_38;
  }
  get _ɵDomRendererFactory2_39():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_39 == null)) { (this.__ɵDomRendererFactory2_39 = new import4.ɵDomRendererFactory2(this._EventManager_37,this._ɵDomSharedStylesHost_38)); }
    return this.__ɵDomRendererFactory2_39;
  }
  get _RendererFactory2_40():any {
    if ((this.__RendererFactory2_40 == null)) { (this.__RendererFactory2_40 = this._ɵDomRendererFactory2_39); }
    return this.__RendererFactory2_40;
  }
  get _ɵSharedStylesHost_41():any {
    if ((this.__ɵSharedStylesHost_41 == null)) { (this.__ɵSharedStylesHost_41 = this._ɵDomSharedStylesHost_38); }
    return this.__ɵSharedStylesHost_41;
  }
  get _Testability_42():import0.Testability {
    if ((this.__Testability_42 == null)) { (this.__Testability_42 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_42;
  }
  get _Meta_43():import4.Meta {
    if ((this.__Meta_43 == null)) { (this.__Meta_43 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_43;
  }
  get _Title_44():import4.Title {
    if ((this.__Title_44 == null)) { (this.__Title_44 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_44;
  }
  get _ɵi_45():import5.ɵi {
    if ((this.__ɵi_45 == null)) { (this.__ɵi_45 = new import5.ɵi()); }
    return this.__ɵi_45;
  }
  get _InMemoryDbService_46():import10.InMemoryDataService {
    if ((this.__InMemoryDbService_46 == null)) { (this.__InMemoryDbService_46 = new import10.InMemoryDataService()); }
    return this.__InMemoryDbService_46;
  }
  get _XHRBackend_48():any {
    if ((this.__XHRBackend_48 == null)) { (this.__XHRBackend_48 = import8.inMemoryBackendServiceFactory(this,this._InMemoryDbService_46,this._InMemoryBackendConfig_47)); }
    return this.__XHRBackend_48;
  }
  get _RequestOptions_49():import6.BaseRequestOptions {
    if ((this.__RequestOptions_49 == null)) { (this.__RequestOptions_49 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_49;
  }
  get _Http_50():any {
    if ((this.__Http_50 == null)) { (this.__Http_50 = import6.ɵc(this._XHRBackend_48,this._RequestOptions_49)); }
    return this.__Http_50;
  }
  get _BrowserXhr_51():import6.BrowserXhr {
    if ((this.__BrowserXhr_51 == null)) { (this.__BrowserXhr_51 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_51;
  }
  get _ResponseOptions_52():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_52 == null)) { (this.__ResponseOptions_52 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_52;
  }
  get _XSRFStrategy_53():any {
    if ((this.__XSRFStrategy_53 == null)) { (this.__XSRFStrategy_53 = import6.ɵb()); }
    return this.__XSRFStrategy_53;
  }
  get _ProductService_54():import11.ProductService {
    if ((this.__ProductService_54 == null)) { (this.__ProductService_54 = new import11.ProductService(this._Http_50)); }
    return this.__ProductService_54;
  }
  get _ActivatedRoute_55():any {
    if ((this.__ActivatedRoute_55 == null)) { (this.__ActivatedRoute_55 = import3.ɵf(this._Router_22)); }
    return this.__ActivatedRoute_55;
  }
  get _NoPreloading_56():import3.NoPreloading {
    if ((this.__NoPreloading_56 == null)) { (this.__NoPreloading_56 = new import3.NoPreloading()); }
    return this.__NoPreloading_56;
  }
  get _PreloadingStrategy_57():any {
    if ((this.__PreloadingStrategy_57 == null)) { (this.__PreloadingStrategy_57 = this._NoPreloading_56); }
    return this.__PreloadingStrategy_57;
  }
  get _RouterPreloader_58():import3.RouterPreloader {
    if ((this.__RouterPreloader_58 == null)) { (this.__RouterPreloader_58 = new import3.RouterPreloader(this._Router_22,this._NgModuleFactoryLoader_20,this._Compiler_19,this,this._PreloadingStrategy_57)); }
    return this.__RouterPreloader_58;
  }
  get _PreloadAllModules_59():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_59 == null)) { (this.__PreloadAllModules_59 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_59;
  }
  get _ROUTER_INITIALIZER_60():any {
    if ((this.__ROUTER_INITIALIZER_60 == null)) { (this.__ROUTER_INITIALIZER_60 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_60;
  }
  get _APP_BOOTSTRAP_LISTENER_61():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_61 == null)) { (this.__APP_BOOTSTRAP_LISTENER_61 = [this._ROUTER_INITIALIZER_60]); }
    return this.__APP_BOOTSTRAP_LISTENER_61;
  }
  get _HeroService_62():import12.HeroService {
    if ((this.__HeroService_62 == null)) { (this.__HeroService_62 = new import12.HeroService(this._Http_50)); }
    return this.__HeroService_62;
  }
  get _HeroDetailGuard_63():import13.HeroDetailGuard {
    if ((this.__HeroDetailGuard_63 == null)) { (this.__HeroDetailGuard_63 = new import13.HeroDetailGuard(this._Router_22)); }
    return this.__HeroDetailGuard_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_10 = new import5.ɵba();
    this._FormsModule_11 = new import5.FormsModule();
    this._HttpModule_12 = new import6.HttpModule();
    this._ɵa_13 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_14 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_15 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_16 = {};
    this._LocationStrategy_17 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_16);
    this._Location_18 = new import2.Location(this._LocationStrategy_17);
    this._Compiler_19 = new import0.Compiler();
    this._NgModuleFactoryLoader_20 = new import0.SystemJsNgModuleLoader(this._Compiler_19,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_21 = [
      [
        {
          path: 'products',
          component: import21.ProductListComponent
        }
        ,
        {
          path: 'products/:id',
          component: import22.ProductDetailComponent
        }
        ,
        {
          path: 'products/:id/edit',
          component: import23.ProductEditComponent
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: '/dashboard',
          pathMatch: 'full'
        }
        ,
        {
          path: 'dashboard',
          component: import24.DashboardComponent,
          data: {title: 'MyData'}
        }
        ,
        {
          path: 'detail/:id',
          canActivate: [import13.HeroDetailGuard],
          component: import25.HeroLiteComponent
        }
        ,
        {
          path: 'heroes',
          component: import26.HeroesComponent
        }

      ]

    ]
    ;
    this._Router_22 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_14,this._RouterOutletMap_15,this._Location_18,this,this._NgModuleFactoryLoader_20,this._Compiler_19,this._ROUTES_21,this._ROUTER_CONFIGURATION_16,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_23 = new import3.RouterModule(this._ɵa_13,this._Router_22);
    this._ProductModule_24 = new import7.ProductModule();
    this._InMemoryWebApiModule_25 = new import8.InMemoryWebApiModule();
    this._AppRoutingModule_26 = new import9.AppRoutingModule();
    this._AppModule_27 = new import1.AppModule();
    this._InMemoryBackendConfig_47 = {delay: 1000};
    return this._AppModule_27;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.ɵba)) { return this._ɵba_10; }
    if ((token === import5.FormsModule)) { return this._FormsModule_11; }
    if ((token === import6.HttpModule)) { return this._HttpModule_12; }
    if ((token === import3.ɵa)) { return this._ɵa_13; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_14; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_15; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_16; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_17; }
    if ((token === import2.Location)) { return this._Location_18; }
    if ((token === import0.Compiler)) { return this._Compiler_19; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_20; }
    if ((token === import3.ROUTES)) { return this._ROUTES_21; }
    if ((token === import3.Router)) { return this._Router_22; }
    if ((token === import3.RouterModule)) { return this._RouterModule_23; }
    if ((token === import7.ProductModule)) { return this._ProductModule_24; }
    if ((token === import8.InMemoryWebApiModule)) { return this._InMemoryWebApiModule_25; }
    if ((token === import9.AppRoutingModule)) { return this._AppRoutingModule_26; }
    if ((token === import1.AppModule)) { return this._AppModule_27; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_28; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_29; }
    if ((token === import0.APP_ID)) { return this._APP_ID_30; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_33; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_34; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_35; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_36; }
    if ((token === import4.EventManager)) { return this._EventManager_37; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_38; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_39; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_40; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_41; }
    if ((token === import0.Testability)) { return this._Testability_42; }
    if ((token === import4.Meta)) { return this._Meta_43; }
    if ((token === import4.Title)) { return this._Title_44; }
    if ((token === import5.ɵi)) { return this._ɵi_45; }
    if ((token === import27.InMemoryDbService)) { return this._InMemoryDbService_46; }
    if ((token === import27.InMemoryBackendConfig)) { return this._InMemoryBackendConfig_47; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_48; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_49; }
    if ((token === import6.Http)) { return this._Http_50; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_51; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_52; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_53; }
    if ((token === import11.ProductService)) { return this._ProductService_54; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_55; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_56; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_57; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_58; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_59; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_60; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_61; }
    if ((token === import12.HeroService)) { return this._HeroService_62; }
    if ((token === import13.HeroDetailGuard)) { return this._HeroDetailGuard_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_38 && this._ɵDomSharedStylesHost_38.ngOnDestroy());
    (this.__RouterPreloader_58 && this._RouterPreloader_58.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvVmlzdWFsIFN0dWRpbyAyMDE3L1Byb2plY3RzL1F1aWNrL1F1aWNrL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9RdWljay9RdWljay9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
