/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './dashboard.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '../../app/dashboard.component';
import * as import5 from '../../app/hero.service';
const styles_DashboardComponent:any[] = [import0.styles];
export const RenderType_DashboardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DashboardComponent,
  data: {}
}
);
function View_DashboardComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),9,'a',[[
        'class',
        'col-1-4'
      ]
    ],[
      [
        1,
        'target',
        0
      ]
      ,
      [
        8,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('click' === en)) {
        const pd_0:any = ((<any>import1.ɵnov(v,1).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import1.ɵdid(335872,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import3.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵpad(2),
    (l()(),import1.ɵted((null as any),['\n        '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'module hero'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n            '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    const currVal_2:any = ck(v,2,0,'/detail',v.context.$implicit.id);
    ck(v,1,0,currVal_2);
  },(ck,v) => {
    const currVal_0:any = import1.ɵnov(v,1).target;
    const currVal_1:any = import1.ɵnov(v,1).href;
    ck(v,0,0,currVal_0,currVal_1);
    const currVal_3:any = v.context.$implicit.name;
    ck(v,7,0,currVal_3);
  });
}
export function View_DashboardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[' Top Heroes'])),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'grid grid-pad'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DashboardComponent_1)),
    import1.ɵdid(401408,(null as any),0,import3.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import4.DashboardComponent = v.component;
    const currVal_0:any = co.heroes;
    ck(v,7,0,currVal_0);
  },(null as any));
}
function View_DashboardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-dashboard',([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,RenderType_DashboardComponent)),
    import1.ɵdid(57344,(null as any),0,import4.DashboardComponent,[
      import5.HeroService,
      import2.ActivatedRoute
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:import1.ComponentFactory<import4.DashboardComponent> = import1.ɵccf('my-dashboard',import4.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvVmlzdWFsIFN0dWRpbyAyMDE3L1Byb2plY3RzL1F1aWNrL1F1aWNrL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9RdWljay9RdWljay9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9RdWljay9RdWljay9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvVmlzdWFsIFN0dWRpbyAyMDE3L1Byb2plY3RzL1F1aWNrL1F1aWNrL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50LnRzLkRhc2hib2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxyXG48aDM+IFRvcCBIZXJvZXM8L2gzPlxyXG48ZGl2IGNsYXNzPVwiZ3JpZCBncmlkLXBhZFwiPlxyXG4gICAgPGEgKm5nRm9yPVwibGV0IGhlcm8gb2YgaGVyb2VzXCIgY2xhc3M9XCJjb2wtMS00XCIgW3JvdXRlckxpbmtdPVwiWycvZGV0YWlsJywgaGVyby5pZF1cIj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kdWxlIGhlcm9cIj5cclxuICAgICAgICAgICAgPGg0Pnt7aGVyby5uYW1lIH19PC9oND5cclxuICAgICAgICA8L2Rpdj5cclxuICAgIDwvYT5cclxuPC9kaXY+IiwiPG15LWRhc2hib2FyZD48L215LWRhc2hib2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0dJO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQStDO0lBQW9DO01BQy9FO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBeUI7SUFDckI7SUFBSTtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQW1CO0lBQ3JCOzs7SUFIcUM7SUFBL0MsU0FBK0MsU0FBL0M7O0lBQUE7SUFBQTtJQUFBLFNBQUEsbUJBQUE7SUFFWTtJQUFBOzs7OztJQUxoQjtJQUNBO0lBQUk7SUFBZ0I7TUFDcEI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyQjtJQUN2QjtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUlJOzs7O0lBSkQ7SUFBSCxTQUFHLFNBQUg7Ozs7O0lDSEo7Z0JBQUE7OztJQUFBO0tBQUE7OztJQUFBOzs7In0=
