/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.crop[_ngcontent-%COMP%] {\r\n    overflow: hidden;\r\n}\r\n\r\ndiv[_ngcontent-%COMP%] {\r\n    cursor: pointer;\r\n}'];
//# sourceMappingURL=star.component.css.shim.ngstyle.js.map